### ISSUE TITLE
编译安装后第一次开启检测到人脸后，会挂掉，

### ISSUE THREAD

**Issue by mmabluesky** [wangjiangyong/tflite_android_facedemo#1]
![image](https://user-images.githubusercontent.com/17948377/51720729-b8876480-2089-11e9-98a2-6f8d5500fe6c.png)

有遇到过吗 ？ 挂在这个函数上    mRecognize->start(ncnn_img1, feature1)

**Comment by wangjiangyong** [comment]
目前没遇到过，debug跟一下代码

**Comment by mmabluesky** [comment]
@wangjiangyong 
感觉这个第一次安装，一旦检测到人脸必定挂mRecognize->start中了 ，第二次开启就很正常

**Comment by mmabluesky** [comment]
已解决，再次感谢大佬的开源精神，，
