### ISSUE TITLE
感觉人脸识别不怎么准确，有时会认错人，是少了人脸对齐这个步骤吗？

### ISSUE THREAD

**Issue by mmabluesky** [wangjiangyong/tflite_android_facedemo#3]
rt ， 我没看懂人脸比对那一块的算法，是根据什么来的呢 ？我尝试着换算成欧式距离 ，结果也不理想 ，如果想在你的基础上优化改进 ，是不是还要加上人脸对齐这个步骤呢

**Comment by wangjiangyong** [comment]
比对使用的余弦距离。 是的，优化可以加上人脸对齐。 也可以考虑参考链接重新训练模型，https://github.com/moli232777144/mobilefacenet-mxnet

**Comment by mmabluesky** [comment]
@wangjiangyong 
tflite 推理得到的人脸数据怎么进行对齐操作呢 ，五个关键点怎么找 ，难道再传到底下用mtcnn中的Onet得到五个关键点 ，然后仿射变换  , 感觉太复杂了
